name: practise
description: "A new Flutter project."


publish_to: 'none' 













version: 1.0.0+1

environment:
  sdk: ^3.7.0-209.1.beta







dependencies:
  flutter:
    sdk: flutter

  
  
  cupertino_icons: ^1.0.8

  ## for statemanament
  get: any

  ## for loading
  flutter_easyloading: ^3.0.0

  ##firebase
  firebase_core: ^3.10.1
  firebase_auth: ^5.4.1
  firebase_messaging: ^15.2.1
  cloud_firestore: ^5.6.2
  firebase_cloud_firestore: ^5.4.4
  google_sign_in: ^6.2.2







dev_dependencies:
  flutter_test:
    sdk: flutter

  
  
  
  
  
  flutter_lints: ^5.0.0





flutter:

  
  
  
  uses-material-design: true

  
  assets:
    - assets/images/
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
