// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAciNdTVlheU1vwOS2OcgAtTJ-UEGFSZw4',
    appId: '1:713870192251:android:031869e664bd64e699fcde',
    messagingSenderId: '713870192251',
    projectId: 'practise-1b628',
    storageBucket: 'practise-1b628.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnQc-GhljTVwFZFiedytWs4mDhsMtCsYM',
    appId: '1:713870192251:web:130fda0dd4dfb0e999fcde',
    messagingSenderId: '713870192251',
    projectId: 'practise-1b628',
    authDomain: 'practise-1b628.firebaseapp.com',
    storageBucket: 'practise-1b628.firebasestorage.app',
    measurementId: 'G-WTYGZNCBLC',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqgCNqVDsFNNY-zaHBnNHh6j16xQYkSh4',
    appId: '1:713870192251:ios:c27c5286bef3eb6a99fcde',
    messagingSenderId: '713870192251',
    projectId: 'practise-1b628',
    storageBucket: 'practise-1b628.firebasestorage.app',
    iosClientId: '713870192251-e5ls6khds9t1c4g305jqn8or87drndan.apps.googleusercontent.com',
    iosBundleId: 'com.example.practise',
  );

}